### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory (bus = smbus.SMBus(1))

### ISSUE THREAD

**Issue by elyerinfox** [Elycin/pihole-stat-rainbow-hat#1]
For those that encountered this error as posted in the description, I encountered this error myself and have asked around in the Pimoroni discord for advice. I was given a pretty simple fix

The error
```
root@raspberrypi:/home/pi# python3 script.py
traceback (most recent call last):
  File "test.py", line 5, in <module>
    import rainbowhat
  File "/usr/lib/python3/dist-packages/rainbowhat/__init__.py", line 31, in <module>
    bus = smbus.SMBus(1)
FileNotFoundError: [Errno 2] No such file or directory
```

The Fix:
1, Edit `/boot/config.txt`
2. Uncomment `dtparam=i2c_arm=on`
3. Reboot.

**Comment by constantnoise** [comment]
Hey,

Loving the script! Finally inspired me to setup Pi-Hole and dust off my Rainbow Hat.

I had the SMBus issue, but couldn't find config.txt in /etc it was in /boot

Thanks for the awesome work!

**Comment by elyerinfox** [comment]
@constantnoise Thanks for mentioning I had the path wrong!

Glad you got to make some use out of your Rainbow HAT :D
